### PR TITLE
Couple more Readme formatting items

### PR DESCRIPTION
**Pull request by mjbear**
To go along with #8, here are a few more Readme formatting items.

* Change distro install grammar
* Fix `.wsl.` to remove the extra trailing period in the inline code fence
* Change "remove container" to a numeric list item
* Put the "temp" dir note into an Alert
* Change nested virt sentence structure
* (later) Move nested virt into an Alert
* (later) Again change the nested virt sentence structure
* Added a space after the greater than symbol in the Alert syntax `> [!NOTE]`
* Standardize unordered list items to hyphens (fix bullets I probably set earlier :neutral_face:, oops)
* Give images a name (as an added plus, it should aid in web page accessibility for anyone with a screen reader)
* Indent some sub-content ([except Alerts](https://github.com/orgs/community/discussions/118296)) beneath related bullet points
* Lint some long Markdown lines
* Reformat Markdown tables based on the [GitHub docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables)

I do have a question about numeric list items which I'll add as a PR response below.

### CODE REVIEW

**Comment by mjbear** [comment]
@kaelemc @FloSch62 
Does it make sense to change numeric list items to `1.` so that the Markdown engine can auto-number?

In the long run if there's an extra step that needs added in the middle this means not having to renumber 3, 4, 5 to 4, 5, 6 for example.

Please let me know and if this is a good idea it can be added to this PR.
Thank you!

**Comment by kaelemc** [comment]
@mjbear Yep, good idea 👍

**Comment by FloSch62** [comment]
Sure, mark it as ready whenever you feel ready 😊

**Comment by mjbear** [comment]
> @mjbear Yep, good idea 👍

It was a great idea _except_ that Alerts (at least currently) don't work when indented.
So there were only a few spots that could be "optimized". Ooops on my part.

Oh well unless GitHub ever fixes the parsing.
For example:

* https://github.com/orgs/community/discussions/118296 <<
* https://github.com/orgs/community/discussions/143379

**Comment by mjbear** [comment]
@kaelemc @FloSch62

Should the line for "Remove the container to ease rebuilding:" become its own numeric bullet point?
(I had already made it a numeric bullet and noticed in the diff that it had not been initially.)

https://github.com/srl-labs/wsl-containerlab/blob/7e54c56beca57d4d091a5438aca19444342ee75f/README.md?plain=1#L230

:point_right: Also, would it make sense for me to add a GitHub Action for Markdown linting?
(Or is that more of a pain for your group?)

**Comment by FloSch62** [comment]
Remove the container to ease rebuilding:" become its own numeric bullet point?

Yes :) thanks 

I think a action for the linting is currently not needed.

**Comment by mjbear** [comment]
Thank you @FloSch62

It's a shame I got bit by Alerts not supporting indenting. Oh well. :neutral_face:

Either way I got some edits in and now I can let you and @kaelemc get back to more important things. :laughing:

All joking aside, thank you for being supportive and welcoming.

**Comment by FloSch62** [comment]
Thanks @mjbear

**Pull request merged**
